# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG POSTGRES_VERSION=13.16
FROM postgres:${POSTGRES_VERSION}

# Copy DB init script
# The postgres entrypoint has to start as root to run the initdb scripts; it drops
# to the postgres user itself before starting the server.
# hadolint ignore=DL3002
USER 0

RUN  mkdir -p /docker-entrypoint-initdb.d

COPY ./scripts/rdbms/init_postgres.sh /docker-entrypoint-initdb.d/

RUN chown -R postgres:postgres /docker-entrypoint-initdb.d/

# Throwaway credential for the local dev database; the same value is baked into the
# compose stack and never leaves it.
# hadolint ignore=DL3064
ENV POSTGRES_PASSWORD=rangerR0cks!
